.TH "_nmeaPOS" 3 "Fri Apr 13 2012" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nmeaPOS \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <info.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBlat\fP"
.br
.ti -1c
.RI "double \fBlon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Position data in fractional degrees or radians 
.PP
Definition at line 41 of file info.h.
.SH "Field Documentation"
.PP 
.SS "double \fB_nmeaPOS::lat\fP"Latitude 
.PP
Definition at line 43 of file info.h.
.SS "double \fB_nmeaPOS::lon\fP"Longitude 
.PP
Definition at line 44 of file info.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
