.TH "_nmeaGPGSV" 3 "Fri Apr 13 2012" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nmeaGPGSV \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sentence.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpack_count\fP"
.br
.ti -1c
.RI "int \fBpack_index\fP"
.br
.ti -1c
.RI "int \fBsat_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GSV packet information structure (Satellites in view) 
.PP
Definition at line 74 of file sentence.h.
.SH "Field Documentation"
.PP 
.SS "int \fB_nmeaGPGSV::pack_count\fP"Total number of messages of this type in this cycle 
.PP
Definition at line 76 of file sentence.h.
.SS "int \fB_nmeaGPGSV::pack_index\fP"Message number 
.PP
Definition at line 77 of file sentence.h.
.SS "int \fB_nmeaGPGSV::sat_count\fP"Total number of satellites in view 
.PP
Definition at line 78 of file sentence.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
