.TH "sentence.h" 3 "Fri Apr 13 2012" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sentence.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'info.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_nmeaGPGGA\fP"
.br
.ti -1c
.RI "struct \fB_nmeaGPGSA\fP"
.br
.ti -1c
.RI "struct \fB_nmeaGPGSV\fP"
.br
.ti -1c
.RI "struct \fB_nmeaGPRMC\fP"
.br
.ti -1c
.RI "struct \fB_nmeaGPVTG\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_nmeaGPGGA\fP \fBnmeaGPGGA\fP"
.br
.ti -1c
.RI "typedef struct \fB_nmeaGPGSA\fP \fBnmeaGPGSA\fP"
.br
.ti -1c
.RI "typedef struct \fB_nmeaGPGSV\fP \fBnmeaGPGSV\fP"
.br
.ti -1c
.RI "typedef struct \fB_nmeaGPRMC\fP \fBnmeaGPRMC\fP"
.br
.ti -1c
.RI "typedef struct \fB_nmeaGPVTG\fP \fBnmeaGPVTG\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBnmeaPACKTYPE\fP { \fBGPNON\fP =  0x0000, \fBGPGGA\fP =  0x0001, \fBGPGSA\fP =  0x0002, \fBGPGSV\fP =  0x0004, \fBGPRMC\fP =  0x0008, \fBGPVTG\fP =  0x0010 }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBsentence.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_nmeaGPGGA\fP  \fBnmeaGPGGA\fP"GGA packet information structure (Global Positioning System Fix Data) 
.SS "typedef struct \fB_nmeaGPGSA\fP  \fBnmeaGPGSA\fP"GSA packet information structure (Satellite status) 
.SS "typedef struct \fB_nmeaGPGSV\fP  \fBnmeaGPGSV\fP"GSV packet information structure (Satellites in view) 
.SS "typedef struct \fB_nmeaGPRMC\fP  \fBnmeaGPRMC\fP"RMC packet information structure (Recommended Minimum sentence C) 
.SS "typedef struct \fB_nmeaGPVTG\fP  \fBnmeaGPVTG\fP"VTG packet information structure (Track made good and ground speed) 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBnmeaPACKTYPE\fP"NMEA packets type which parsed and generated by library 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIGPNON \fP\fP
Unknown packet type. 
.TP
\fB\fIGPGGA \fP\fP
GGA - Essential fix data which provide 3D location and accuracy data. 
.TP
\fB\fIGPGSA \fP\fP
GSA - GPS receiver operating mode, SVs used for navigation, and DOP values. 
.TP
\fB\fIGPGSV \fP\fP
GSV - Number of SVs in view, PRN numbers, elevation, azimuth & SNR values. 
.TP
\fB\fIGPRMC \fP\fP
RMC - Recommended Minimum Specific GPS/TRANSIT Data. 
.TP
\fB\fIGPVTG \fP\fP
VTG - Actual track made good and speed over ground. 
.PP
Definition at line 25 of file sentence.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
