.TH "time.h" 3 "Fri Apr 13 2012" "Version 0.5.3" "NMEA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
time.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_nmeaTIME\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_nmeaTIME\fP \fBnmeaTIME\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnmea_time_now\fP (\fBnmeaTIME\fP *t)"
.br
.RI "\fIGet time now to nmeaTIME structure. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBtime.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_nmeaTIME\fP  \fBnmeaTIME\fP"Date and time data 
.PP
\fBSee also:\fP
.RS 4
\fBnmea_time_now\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for NMEA from the source code.
